"""Org-namespace username validator + Wave 0 user-model additions."""
import pytest
from django.core.exceptions import ValidationError

from stapel_core.django.users.models import AbstractStapelUser
from stapel_core.django.users.validators import StapelUsernameValidator

validator = StapelUsernameValidator()

VALID = [
    "victor",  # bare username, stock canon
    "user_ab12cd34",  # autogenerated shape
    "j.doe+test@x-1",  # full stock alphabet
    "acme/victor",  # org-namespaced login
    "acme-corp/j.doe",  # slug chars left, stock canon right
    "org_1/user_2",
]

INVALID = [
    "",  # empty
    "/victor",  # leading slash
    "victor/",  # trailing slash
    "acme//victor",  # double slash
    "a/b/c",  # more than one separator
    "/",  # separator only
    "acme/vic tor",  # invalid char in local part
    "acme/vic#tor",  # invalid char in local part
    "ac me/victor",  # invalid char in org part
    "vic tor",  # bare username still rejects invalid chars
]


@pytest.mark.parametrize("value", VALID)
def test_valid_usernames(value):
    validator(value)  # must not raise


@pytest.mark.parametrize("value", INVALID)
def test_invalid_usernames(value):
    with pytest.raises(ValidationError):
        validator(value)


def test_model_username_field_carries_the_validator(db):
    from django.contrib.auth import get_user_model

    field = get_user_model()._meta.get_field("username")
    assert any(isinstance(v, StapelUsernameValidator) for v in field.validators)
    # and the stock validator (which forbids "/") is gone
    from django.contrib.auth.validators import UnicodeUsernameValidator

    assert not any(type(v) is UnicodeUsernameValidator for v in field.validators)


def test_namespaced_user_passes_full_clean(db):
    from django.contrib.auth import get_user_model

    user = get_user_model()(username="acme/victor", auth_type="login")
    user.full_clean(exclude=["password"])  # must not raise


def test_double_slash_user_fails_full_clean(db):
    from django.contrib.auth import get_user_model

    user = get_user_model()(username="acme//victor", auth_type="login")
    with pytest.raises(ValidationError):
        user.full_clean(exclude=["password"])


def test_auth_type_login_choice_present():
    assert ("login", "Login") in AbstractStapelUser.AUTH_TYPE_CHOICES


def test_first_login_policy_flags_default_false(db):
    from django.contrib.auth import get_user_model

    user = get_user_model().objects.create(username="acme/provisioned", auth_type="login")
    assert user.password_change_required is False
    assert user.mfa_enrollment_required is False
