# Generated by Django 5.2.8 on 2026-02-10 09:28
#
# stapel: contract-phase
# verified: this migration shipped in stapel-core's first commit/release
# (v0.2.0+; extracted from the monolith) — no released version of this
# package predates it. Current django/users/models.py already declares
# phone = CharField(max_length=18, ...), matching the narrowed width, and
# existing data is normalized via RunPython below while the column is still
# varchar(20), before the AlterField narrows it.

import re
from django.db import migrations, models


def normalize_phones(apps, schema_editor):
    """Normalize existing phone numbers: strip spaces, dashes, parens."""
    User = apps.get_model('users', 'User')
    for user in User.objects.exclude(phone__isnull=True).exclude(phone=''):
        # Remove all non-digit characters except leading +
        phone = user.phone.strip()
        if phone.startswith('+'):
            normalized = '+' + re.sub(r'[^\d]', '', phone[1:])
        else:
            normalized = re.sub(r'[^\d]', '', phone)
        if normalized != user.phone:
            User.objects.filter(pk=user.pk).update(phone=normalized)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_unique_constraints'),
    ]

    operations = [
        # First normalize data while column is still varchar(20)
        migrations.RunPython(normalize_phones, migrations.RunPython.noop),
        # Then shrink column
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
