# Generated by Django 6.0.7 on 2026-07-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_widen_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_type',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('oauth', 'OAuth'), ('sso', 'SSO'), ('anonymous', 'Anonymous')], default='email', max_length=20),
        ),
    ]
