# Generated by Django 6.0.7 on 2026-07-24 11:48

import stapel_core.django.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_auth_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_enrollment_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='password_change_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_type',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('oauth', 'OAuth'), ('sso', 'SSO'), ('anonymous', 'Anonymous'), ('login', 'Login')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ characters, with at most one '/' as an organization separator.", max_length=150, unique=True, validators=[stapel_core.django.users.validators.StapelUsernameValidator()], verbose_name='username'),
        ),
    ]
