"""PostgreSQL time-partitioning for the event table — SQL generation.

The default backend's raw table is huge and append-only, so on PostgreSQL it
is partitioned by ``ts`` range (drop-old = ``DROP PARTITION``, cheap; the
planner prunes by time window). Django has no declarative partitioning, so
the DDL is generated here and applied operationally:

- convert the plain table into a partitioned parent once (``parent_ddl`` — an
  ops/RunSQL step, since it re-creates the table);
- create upcoming period partitions ahead of time (``ensure_partitions_sql``,
  driven by ``manage.py eventstore_partition``).

On the SQLite minimal profile none of this runs — the Django-managed table
stays a single plain table (documented degradation). These functions are
pure string builders so they are unit-testable without a live PostgreSQL.
"""
from __future__ import annotations

from datetime import date, datetime, timedelta, timezone

#: Default physical table name of ``EventRecord`` (``<app_label>_<model>``).
DEFAULT_TABLE = "stapel_eventstore_eventrecord"


def _month_start(d: date) -> date:
    return d.replace(day=1)


def _next_month(d: date) -> date:
    return date(d.year + 1, 1, 1) if d.month == 12 else date(d.year, d.month + 1, 1)


def period_bounds(moment: datetime, period: str = "month") -> tuple[date, date, str]:
    """Half-open ``[start, end)`` and a partition suffix for *moment*.

    ``month`` → ``[YYYY-MM-01, next-month-01)`` suffix ``pYYYYMM``;
    ``day``   → ``[YYYY-MM-DD, +1 day)``        suffix ``pYYYYMMDD``.
    """
    d = moment.date()
    if period == "day":
        start = d
        end = d + timedelta(days=1)
        return start, end, f"p{start:%Y%m%d}"
    if period == "month":
        start = _month_start(d)
        end = _next_month(start)
        return start, end, f"p{start:%Y%m}"
    raise ValueError(f"unknown partition period {period!r} (use 'month' or 'day')")


def parent_ddl(table: str = DEFAULT_TABLE) -> str:
    """DDL that (re)creates *table* as a range-partitioned parent on ``ts``.

    Operational one-time step (data migration): the plain table cannot be
    altered into a partitioned one in place. Column list mirrors
    ``EventRecord``; the primary key includes ``ts`` because PostgreSQL
    requires the partition key in every unique/primary key.
    """
    return (
        f"CREATE TABLE {table} (\n"
        "    id bigint GENERATED BY DEFAULT AS IDENTITY,\n"
        "    stream varchar(255) NOT NULL,\n"
        "    ts timestamptz NOT NULL,\n"
        "    payload jsonb NOT NULL DEFAULT '{}',\n"
        "    project varchar(255) NULL,\n"
        "    task varchar(255) NULL,\n"
        "    container varchar(255) NULL,\n"
        "    PRIMARY KEY (id, ts)\n"
        ") PARTITION BY RANGE (ts);"
    )


def create_partition_sql(
    start: date, end: date, suffix: str, table: str = DEFAULT_TABLE
) -> str:
    """``CREATE TABLE IF NOT EXISTS`` one partition covering ``[start, end)``."""
    return (
        f"CREATE TABLE IF NOT EXISTS {table}_{suffix} "
        f"PARTITION OF {table} "
        f"FOR VALUES FROM ('{start:%Y-%m-%d}') TO ('{end:%Y-%m-%d}');"
    )


def ensure_partitions_sql(
    *,
    start: datetime | None = None,
    periods_ahead: int = 3,
    period: str = "month",
    table: str = DEFAULT_TABLE,
) -> list[str]:
    """SQL to create the current partition plus *periods_ahead* future ones.

    Idempotent (``IF NOT EXISTS``); run on a schedule so writes always land
    in an existing partition.
    """
    now = start or datetime.now(timezone.utc)
    statements: list[str] = []
    cursor = now
    for _ in range(max(1, periods_ahead + 1)):
        p_start, p_end, suffix = period_bounds(cursor, period)
        statements.append(create_partition_sql(p_start, p_end, suffix, table))
        # advance one period past the end of the one we just made
        cursor = datetime(p_end.year, p_end.month, p_end.day, tzinfo=timezone.utc)
    return statements


def drop_partition_sql(suffix: str, table: str = DEFAULT_TABLE) -> str:
    """``DROP TABLE`` a single expired partition (retention by partition)."""
    return f"DROP TABLE IF EXISTS {table}_{suffix};"


__all__ = [
    "DEFAULT_TABLE",
    "create_partition_sql",
    "drop_partition_sql",
    "ensure_partitions_sql",
    "parent_ddl",
    "period_bounds",
]
